In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv("amazon_prime.csv")

In [ ]:
data.head()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts20945,The Three Stooges,SHOW,The Three Stooges were an American vaudeville ...,1934,TV-PG,19,"['comedy', 'family', 'animation', 'action', 'f...",['US'],26.0,tt0850645,8.6,1092.0,15.424,7.6
1,tm19248,The General,MOVIE,"During America’s Civil War, Union spies steal ...",1926,NaN,78,"['action', 'drama', 'war', 'western', 'comedy'...",['US'],NaN,tt0017925,8.2,89766.0,8.647,8.0
2,tm82253,The Best Years of Our Lives,MOVIE,It's the hope that sustains the spirit of ever...,1946,NaN,171,"['romance', 'war', 'drama']",['US'],NaN,tt0036868,8.1,63026.0,8.435,7.8
3,tm83884,His Girl Friday,MOVIE,"Hildy, the journalist former wife of newspaper...",1940,NaN,92,"['comedy', 'drama', 'romance']",['US'],NaN,tt0032599,7.8,57835.0,11.270,7.4
4,tm56584,In a Lonely Place,MOVIE,An aspiring actress begins to suspect that her...,1950,NaN,94,"['thriller', 'drama', 'romance']",['US'],NaN,tt0042593,7.9,30924.0,8.273,7.6

In [ ]:
data['imdb_score']=data['imdb_score'].fillna(data['imdb_score'].mean())
data

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts20945,The Three Stooges,SHOW,The Three Stooges were an American vaudeville ...,1934,TV-PG,19,"['comedy', 'family', 'animation', 'action', 'f...",['US'],26.0,tt0850645,8.600000,1092.0,15.424,7.6
1,tm19248,The General,MOVIE,"During America’s Civil War, Union spies steal ...",1926,NaN,78,"['action', 'drama', 'war', 'western', 'comedy'...",['US'],NaN,tt0017925,8.200000,89766.0,8.647,8.0
2,tm82253,The Best Years of Our Lives,MOVIE,It's the hope that sustains the spirit of ever...,1946,NaN,171,"['romance', 'war', 'drama']",['US'],NaN,tt0036868,8.100000,63026.0,8.435,7.8
3,tm83884,His Girl Friday,MOVIE,"Hildy, the journalist former wife of newspaper...",1940,NaN,92,"['comedy', 'drama', 'romance']",['US'],NaN,tt0032599,7.800000,57835.0,11.270,7.4
4,tm56584,In a Lonely Place,MOVIE,An aspiring actress begins to suspect that her...,1950,NaN,94,"['thriller', 'drama', 'romance']",['US'],NaN,tt0042593,7.900000,30924.0,8.273,7.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9866,tm510327,Lily Is Here,MOVIE,Dallas and heroin have one thing in common: Du...,2021,NaN,93,['drama'],['US'],NaN,tt7672388,5.300000,20.0,1.406,NaN
9867,tm1079144,Jay Nog: Something from Nothing,MOVIE,Something From Nothing takes you on a stand-up...,2021,NaN,55,['comedy'],['US'],NaN,tt15041600,5.976395,NaN,0.600,NaN
9868,tm847725,Chasing,MOVIE,A cop from Chennai sets out to nab a dreaded d...,2021,NaN,116,['crime'],['IN'],NaN,NaN,5.976395,NaN,1.960,NaN
9869,tm1054116,Baikunth,MOVIE,"This story is about prevalent caste problem, e...",2021,NaN,72,"['family', 'drama']",[],NaN,tt14331982,8.400000,49.0,0.645,NaN
9870,ts275838,Waking Up Eighty,SHOW,"Kara Stewart, 16, is fed up with just about ev...",2021,NaN,10,['drama'],[],1.0,tt13542552,5.976395,NaN,NaN,NaN

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9871 entries, 0 to 9870
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    9871 non-null   object
 1   title                 9871 non-null   object
 2   type                  9871 non-null   object
 3   description           9752 non-null   object
 4   release_year          9871 non-null   int64
 5   age_certification     3384 non-null   object
 6   runtime               9871 non-null   int64
 7   genres                9871 non-null   object
 8   production_countries  9871 non-null   object
 9   seasons               1357 non-null   float64
 10  imdb_id               9204 non-null   object
 11  imdb_score            9871 non-null   float64
 12  imdb_votes            8840 non-null   float64
 13  tmdb_popularity       9324 non-null   float64
 14  tmdb_score            7789 non-null   float64
dtypes: float64(5), int64(2), object(8)
memory usage: 1.1+ MB

In [ ]:
a=data.pivot_table(columns='type',values='imdb_score',aggfunc=(np.mean))
a

type           MOVIE      SHOW
imdb_score  5.820003  6.957621

In [ ]:
comedy=data[data['genres'].str.contains('comedy')]
comedy

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts20945,The Three Stooges,SHOW,The Three Stooges were an American vaudeville ...,1934,TV-PG,19,"['comedy', 'family', 'animation', 'action', 'f...",['US'],26.0,tt0850645,8.600000,1092.0,15.424,7.6
1,tm19248,The General,MOVIE,"During America’s Civil War, Union spies steal ...",1926,NaN,78,"['action', 'drama', 'war', 'western', 'comedy'...",['US'],NaN,tt0017925,8.200000,89766.0,8.647,8.0
3,tm83884,His Girl Friday,MOVIE,"Hildy, the journalist former wife of newspaper...",1940,NaN,92,"['comedy', 'drama', 'romance']",['US'],NaN,tt0032599,7.800000,57835.0,11.270,7.4
6,tm87233,It's a Wonderful Life,MOVIE,A holiday favourite for generations... George...,1946,PG,130,"['drama', 'family', 'fantasy', 'romance', 'com...",['US'],NaN,tt0038650,8.600000,444243.0,26.495,8.3
8,tm116781,My Man Godfrey,MOVIE,"Fifth Avenue socialite Irene Bullock needs a ""...",1936,NaN,95,"['comedy', 'romance', 'drama']",['US'],NaN,tt0028010,8.000000,23532.0,8.633,7.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9843,tm616953,Ammaa Ki Boli,MOVIE,Interesting story about the series of events t...,2021,NaN,117,"['comedy', 'drama']",['IN'],NaN,tt2211174,7.300000,1335.0,2.382,1.0
9847,tm1098070,Girls' Night In,MOVIE,Three women who have been friends since childh...,2021,NaN,91,"['comedy', 'drama']",['US'],NaN,tt9684806,2.800000,28.0,1.306,7.0
9858,ts320425,Funny Little Stories,SHOW,NaN,2021,NaN,28,['comedy'],['PT'],1.0,NaN,5.976395,NaN,0.600,NaN
9863,tm1078263,Good Boys for Life,MOVIE,"Toddrick Frank, a hustler, living his life unt...",2021,NaN,73,"['comedy', 'drama']",['US'],NaN,tt15000128,3.900000,50.0,2.076,NaN
9867,tm1079144,Jay Nog: Something from Nothing,MOVIE,Something From Nothing takes you on a stand-up...,2021,NaN,55,['comedy'],['US'],NaN,tt15041600,5.976395,NaN,0.600,NaN

In [ ]:
data['genres']=data['genres'].apply(eval)
l=[]
for i in data['genres']:
  for j in i:
    if j not in l:
      l.append(j)
print(l)

['comedy', 'family', 'animation', 'action', 'fantasy', 'horror', 'drama', 'war', 'western', 'european', 'romance', 'thriller', 'crime', 'history', 'sport', 'scifi', 'documentation', 'music', 'reality']

In [ ]:
release=data[data['release_year']>2000]
release

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
2805,tm81482,The Passion of the Christ,MOVIE,A graphic portrayal of the last twelve hours o...,2004,R,126,[drama],['US'],NaN,tt0335345,7.200000,229777.0,87.014,7.4
2806,ts11,Downton Abbey,SHOW,A chronicle of the lives of the aristocratic C...,2010,TV-14,58,"[drama, romance, european]",['GB'],6.0,tt1606375,8.700000,197744.0,57.029,8.1
2807,ts21483,How I Met Your Mother,SHOW,A father recounts to his children - through a ...,2005,TV-14,24,"[comedy, romance]",['US'],9.0,tt0460649,8.300000,661972.0,153.898,8.2
2808,ts22280,House,SHOW,"Dr. Gregory House, a drug-addicted, unconventi...",2004,TV-14,44,"[drama, comedy]",['US'],8.0,tt0412142,8.700000,448480.0,286.211,8.6
2809,ts21608,Scrubs,SHOW,"In the unreal world of Sacred Heart Hospital, ...",2001,TV-14,24,"[comedy, drama]",['US'],9.0,tt0285403,8.400000,251172.0,73.230,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9866,tm510327,Lily Is Here,MOVIE,Dallas and heroin have one thing in common: Du...,2021,NaN,93,[drama],['US'],NaN,tt7672388,5.300000,20.0,1.406,NaN
9867,tm1079144,Jay Nog: Something from Nothing,MOVIE,Something From Nothing takes you on a stand-up...,2021,NaN,55,[comedy],['US'],NaN,tt15041600,5.976395,NaN,0.600,NaN
9868,tm847725,Chasing,MOVIE,A cop from Chennai sets out to nab a dreaded d...,2021,NaN,116,[crime],['IN'],NaN,NaN,5.976395,NaN,1.960,NaN
9869,tm1054116,Baikunth,MOVIE,"This story is about prevalent caste problem, e...",2021,NaN,72,"[family, drama]",[],NaN,tt14331982,8.400000,49.0,0.645,NaN
9870,ts275838,Waking Up Eighty,SHOW,"Kara Stewart, 16, is fed up with just about ev...",2021,NaN,10,[drama],[],1.0,tt13542552,5.976395,NaN,NaN,NaN

In [ ]:
new=data[data['genres']!='[]']
new

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts20945,The Three Stooges,SHOW,The Three Stooges were an American vaudeville ...,1934,TV-PG,19,"[comedy, family, animation, action, fantasy, h...",['US'],26.0,tt0850645,8.600000,1092.0,15.424,7.6
1,tm19248,The General,MOVIE,"During America’s Civil War, Union spies steal ...",1926,NaN,78,"[action, drama, war, western, comedy, european]",['US'],NaN,tt0017925,8.200000,89766.0,8.647,8.0
2,tm82253,The Best Years of Our Lives,MOVIE,It's the hope that sustains the spirit of ever...,1946,NaN,171,"[romance, war, drama]",['US'],NaN,tt0036868,8.100000,63026.0,8.435,7.8
3,tm83884,His Girl Friday,MOVIE,"Hildy, the journalist former wife of newspaper...",1940,NaN,92,"[comedy, drama, romance]",['US'],NaN,tt0032599,7.800000,57835.0,11.270,7.4
4,tm56584,In a Lonely Place,MOVIE,An aspiring actress begins to suspect that her...,1950,NaN,94,"[thriller, drama, romance]",['US'],NaN,tt0042593,7.900000,30924.0,8.273,7.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9866,tm510327,Lily Is Here,MOVIE,Dallas and heroin have one thing in common: Du...,2021,NaN,93,[drama],['US'],NaN,tt7672388,5.300000,20.0,1.406,NaN
9867,tm1079144,Jay Nog: Something from Nothing,MOVIE,Something From Nothing takes you on a stand-up...,2021,NaN,55,[comedy],['US'],NaN,tt15041600,5.976395,NaN,0.600,NaN
9868,tm847725,Chasing,MOVIE,A cop from Chennai sets out to nab a dreaded d...,2021,NaN,116,[crime],['IN'],NaN,NaN,5.976395,NaN,1.960,NaN
9869,tm1054116,Baikunth,MOVIE,"This story is about prevalent caste problem, e...",2021,NaN,72,"[family, drama]",[],NaN,tt14331982,8.400000,49.0,0.645,NaN
9870,ts275838,Waking Up Eighty,SHOW,"Kara Stewart, 16, is fed up with just about ev...",2021,NaN,10,[drama],[],1.0,tt13542552,5.976395,NaN,NaN,NaN

In [ ]:
new.tail()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
9866,tm510327,Lily Is Here,MOVIE,Dallas and heroin have one thing in common: Du...,2021,NaN,93,[drama],['US'],NaN,tt7672388,5.300000,20.0,1.406,NaN
9867,tm1079144,Jay Nog: Something from Nothing,MOVIE,Something From Nothing takes you on a stand-up...,2021,NaN,55,[comedy],['US'],NaN,tt15041600,5.976395,NaN,0.600,NaN
9868,tm847725,Chasing,MOVIE,A cop from Chennai sets out to nab a dreaded d...,2021,NaN,116,[crime],['IN'],NaN,NaN,5.976395,NaN,1.960,NaN
9869,tm1054116,Baikunth,MOVIE,"This story is about prevalent caste problem, e...",2021,NaN,72,"[family, drama]",[],NaN,tt14331982,8.400000,49.0,0.645,NaN
9870,ts275838,Waking Up Eighty,SHOW,"Kara Stewart, 16, is fed up with just about ev...",2021,NaN,10,[drama],[],1.0,tt13542552,5.976395,NaN,NaN,NaN

In [ ]:
new.drop(['age_certification'],axis=1)

,id,title,type,description,release_year,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts20945,The Three Stooges,SHOW,The Three Stooges were an American vaudeville ...,1934,19,"[comedy, family, animation, action, fantasy, h...",['US'],26.0,tt0850645,8.600000,1092.0,15.424,7.6
1,tm19248,The General,MOVIE,"During America’s Civil War, Union spies steal ...",1926,78,"[action, drama, war, western, comedy, european]",['US'],NaN,tt0017925,8.200000,89766.0,8.647,8.0
2,tm82253,The Best Years of Our Lives,MOVIE,It's the hope that sustains the spirit of ever...,1946,171,"[romance, war, drama]",['US'],NaN,tt0036868,8.100000,63026.0,8.435,7.8
3,tm83884,His Girl Friday,MOVIE,"Hildy, the journalist former wife of newspaper...",1940,92,"[comedy, drama, romance]",['US'],NaN,tt0032599,7.800000,57835.0,11.270,7.4
4,tm56584,In a Lonely Place,MOVIE,An aspiring actress begins to suspect that her...,1950,94,"[thriller, drama, romance]",['US'],NaN,tt0042593,7.900000,30924.0,8.273,7.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9866,tm510327,Lily Is Here,MOVIE,Dallas and heroin have one thing in common: Du...,2021,93,[drama],['US'],NaN,tt7672388,5.300000,20.0,1.406,NaN
9867,tm1079144,Jay Nog: Something from Nothing,MOVIE,Something From Nothing takes you on a stand-up...,2021,55,[comedy],['US'],NaN,tt15041600,5.976395,NaN,0.600,NaN
9868,tm847725,Chasing,MOVIE,A cop from Chennai sets out to nab a dreaded d...,2021,116,[crime],['IN'],NaN,NaN,5.976395,NaN,1.960,NaN
9869,tm1054116,Baikunth,MOVIE,"This story is about prevalent caste problem, e...",2021,72,"[family, drama]",[],NaN,tt14331982,8.400000,49.0,0.645,NaN
9870,ts275838,Waking Up Eighty,SHOW,"Kara Stewart, 16, is fed up with just about ev...",2021,10,[drama],[],1.0,tt13542552,5.976395,NaN,NaN,NaN

In [ ]:
new.to_csv("new_data_amazon")